import assert from 'node:assert/strict';
import test from 'node:test';
import {createHash} from 'node:crypto';
import * as THREE from 'three';
import {createV14dGameAppearanceAdapter} from '../src/features/stage/v14dGameAppearanceAdapter.js';
import {createV14dGameMaterials} from '../src/features/stage/v14dGameMaterials.js';
import {getStagePresentationConfig} from '../src/features/stage/mmdCompanionRuntime.js';
import {V14D_GAME_DEFAULT_SETTINGS} from '../src/features/stage/v14dGameAppearanceAssets.js';
const bytes=new TextEncoder().encode(JSON.stringify({lights:[]}));
const sha=createHash('sha256').update(bytes).digest('hex');
const entry={url:'http://local/source',sha256:sha};
const manifest={available:true,id:'fixture',sourceManifestSha256:sha,model:{url:'/koleda.pmx',relativePath:'koleda.pmx',sha256:sha},textures:[{...entry,key:'texture',kind:'normal'}],ocio:Object.fromEntries(['processor','shader','lut0','lut1'].map(k=>[k,entry])),materialSource:entry,masks:Array.from({length:5},()=>entry),lights:Array.from({length:6},()=>({type:'AREA',shape:'DISK',color:[1,1,1],matrix:[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]],size:1,sizeY:1,power:10}))};
const runtime={renderer:{},v14dGameLights:Array(6).fill({})};
const fetchImpl=async()=>new Response(bytes);
test('默认状态和非目标模型拒绝',async()=>{const a=createV14dGameAppearanceAdapter();assert.equal(a.getStatus().realAppearanceAvailable,false);assert.deepEqual(a.getStatus().settings,V14D_GAME_DEFAULT_SETTINGS);assert.equal((await a.install({model:{name:'Other'},modelUrl:'/other.pmx'})).phase,'unsupported');});
test('资源清单缺少遮罩时不能声明外观就绪',async()=>{const a=createV14dGameAppearanceAdapter({manifest:{...manifest,masks:[]}});const s=await a.install({model:{name:'koleda'},runtime});assert.equal(s.phase,'unavailable');assert.equal(s.realAppearanceAvailable,false);});
test('材质工厂替换和释放恢复原材质引用',async()=>{const original=[new THREE.MeshToonMaterial()],replacement=[new THREE.MeshPhysicalMaterial()];let disposed=0;const a=createV14dGameAppearanceAdapter({manifest,fetchImpl,createMaterials:async()=>({materials:replacement,dispose(){disposed++;},evidence:()=>({maskCount:5}),draw:fn=>fn()})});const model={name:'koleda',material:original};assert.equal((await a.install({model,runtime})).phase,'ready');assert.equal(model.material,replacement);assert.equal(a.draw(()=>42),42);a.release();assert.equal(model.material,original);assert.equal(disposed,1);assert.equal(a.getStatus().realAppearanceAvailable,false);});
test('销毁期间迟到材质不能挂回模型',async()=>{let finish,entered;const arrived=new Promise(r=>entered=r);const original=[];let disposed=0;const a=createV14dGameAppearanceAdapter({manifest,fetchImpl,createMaterials:()=>{entered();return new Promise(r=>finish=r);}});const model={name:'koleda',material:original};const pending=a.install({model,runtime});await arrived;a.release();finish({materials:[],dispose(){disposed++;}});await pending;assert.equal(model.material,original);assert.equal(disposed,1);assert.equal(a.getStatus().installed,false);});
test('源材质哈希不符拒绝，不只检查清单存在',async()=>{const a=createV14dGameAppearanceAdapter({manifest,fetchImpl:async()=>new Response('wrong')});const s=await a.install({model:{name:'koleda'},runtime});assert.equal(s.phase,'unavailable');assert.match(s.reason,/哈希/);});
test('真实工厂创建物理材质并临时覆盖表情，绘制异常也恢复',async()=>{
 const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute([0,19,0,1,19,0,0,11,0],3));geometry.setIndex([0,1,2]);geometry.addGroup(0,3,0);
 const map=new THREE.Texture({width:4,height:4}),original=[new THREE.MeshToonMaterial({name:'HairA',map}),new THREE.MeshToonMaterial({name:'Cth1-Top',map}),new THREE.MeshToonMaterial({name:'Face',map})];
 const model=new THREE.Mesh(geometry,original),head=new THREE.Bone();head.name='頭';model.add(head);model.skeleton={bones:[head]};model.morphTargetDictionary={'まばたき':0,'口角上げ':1};model.morphTargetInfluences=[.2,.3];
 const material={tint:[.8,.8,1],roughness:.34,specularLevel:.38,toonMix:.38,ramp:[{position:0,color:[.5,.5,.6]},{position:.4,color:[1,1,1]}],emissionBranch:'ramp'};
 const source={lights:manifest.lights,materials:{HairA:material,Face:{...material,emissionBranch:'masked-face-color'}},referenceVisiblePolygonCounts:{}};
 const factory=await createV14dGameMaterials({model,manifest:source,renderer:{capabilities:{getMaxAnisotropy:()=>8},getPixelRatio:()=>1},settings:{...V14D_GAME_DEFAULT_SETTINGS},loadTexture:async()=>new THREE.Texture({width:4,height:4}),maskEntries:manifest.masks,lights:[]});
 assert.ok(factory.materials.every(m=>m.isMeshPhysicalMaterial));assert.equal(map.colorSpace,THREE.SRGBColorSpace);assert.ok(factory.materials[1].normalMap);assert.equal(factory.evidence().maskCount,5);
 assert.throws(()=>factory.draw(()=>{assert.deepEqual(model.morphTargetInfluences,[1,.55]);throw Error('draw-failure');}),/draw-failure/);assert.deepEqual(model.morphTargetInfluences,[.2,.3]);factory.draw(()=>assert.deepEqual(model.morphTargetInfluences,[1,.3]),{speaking:true});factory.dispose();assert.equal(map.colorSpace,THREE.NoColorSpace);assert.equal(geometry.getAttribute('gameHairMask'),undefined);
});
test('新模式保留透明背景且不改经典模式配置',()=>{const game=getStagePresentationConfig('v14d-game');assert.equal(game.background,null);assert.equal(game.postfx.enabled,false);assert.notDeepEqual(game,getStagePresentationConfig('classic'));});
